#!/usr/bin/env bash

## Install ansible
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    sudo apt-add-repository -y ppa:ansible/ansible
    sudo apt-get update -y
    sudo apt-get install -y curl git software-properties-common ansible
elif [[ "$OSTYPE" == "darwin"* ]]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    brew install ansible
elif [ -f "/etc/arch-release" ]; then
    sudo pacman -S ansible-core ansible
fi

## pull ansible
# sudo ansible-pull -U https://github.com/MathieuTuli/ansible.git
