- name: Installing stow
  apt: name=stow
  when: ansible_facts['distribution'] == "Ubuntu"
  tags:
    - install
    - dotfiles
    - stow
- name: Installing stow
  pacman: name=stow
  when: ansible_facts['os_family'] == "ArchLinux"
  tags:
    - install
    - dotfiles
    - stow
- name: Installing stow
  community.general.homebrew:
    name: foo
    state: present
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:MathieuTuli/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install
  tags:
    - install
    - dotfiles
    - stow
